### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by c0cee** [sabrsorensen/alpine-plex_autoscan#8]
```
OS: Ubuntnu 18.04.5 LTS bionic
Plex Docker Image: linuxserver/plex Version 1.20.1.3252-a78fef9a9-ls116
```

Im getting the following error while trying to deploy the container for plex_autoscan

```
/bin/importas: line 1: syntax error: unexpected word (expecting ")")

/init: export: line 12: /opt/plex_autoscan:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin: bad variable name
```

I tried to deploy it with Portainer and via cli with the following command
```
sudo docker run -d \
    -p 3468:3468 \
    --name=autoscan \
    -v /root/mnt/PTD:/data \
    -v /root/configs/plex_autoscan:/config \
    -v "/root/configs/plex/Library/Application Support/Plex Media Server/Plug-in Support/Databases":/plexDb \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e PUID=0 \
    -e PGID=0 \
    sabrsorensen/alpine-plex_autoscan
```

The Media of my Plex Server is mounted on Google Drive via rclone mount. 
I checked the my config file multiple times if there is any issue but didnt find anything so far.
[config.json on pastbin.com](https://pastebin.com/LYcPi20W)

**Comment by sabrsorensen** [comment]
This appears to be an issue with s6-overlay, used to manage the service processes in the container, before plex_autoscan is initialized. Although PATH looks as expected, for some reason /init is expanding it instead of reading it as a variable name. I haven't been able to reproduce this locally with the latest image, what image version are you using? `docker inspect sabrsorensen/alpine-plex_autoscan --format '{{ index .Config.Labels "org.label-schema.vcs-ref"}}'`

**Comment by ghost** [comment]
Thank you for the reply!
Im using the image version 242b871826c00bd16df30f0fa9a6ec01a1c8afa0 on a Raspberry Pi 4

**Comment by sabrsorensen** [comment]
This seems like an issue with me incorrectly using the amd64 s6-overlay for all architectures, rather than downloading the correct release for the target OS.

I will work on fixing the arm64 build to use the armhf build of s6-overlay, indicated to be compatible with the Raspberry Pi.

Thanks for the feedback and info!

**Comment by sabrsorensen** [comment]
@c0cee try using tag 13b9683 or later once the build is available, I believe the correct architecture of s6-overlay is now used.
